#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	AFTERIMAGEMANAGERSCRIPT,
	AFTERIMAGESCRIPT,
	AIMMINGRAYSCRIPT,
	ARMSCRIPT,
	ARMTOGRABLINESCRIPT,
	BACKGROUNDSCRIPT,
	BOMBCARGOSCRIPT,
	BOMBSCRIPT,
	BOSSATSCRIPT,
	BOSSP2ALERTSCRIPT,
	BOSSROOMSYSMGRSCRIPT,
	BOSSSCRIPT,
	BOSSWAVESCRIPT,
	BROKENCARGOSCRIPT,
	BULLETSCRIPT,
	BUTTONSCRIPT,
	CAMERASCRIPT,
	CAPESCRIPT,
	CHAINSCRIPT,
	CLIMBBARSCRIPT,
	CURSORSCRIPT,
	DEATHCOLSCRIPT,
	DEFENDSCRIPT,
	DESTUISCRIPT,
	DROPREDCARGOCOLSCRIPT,
	DROPREDCARGOSCRIPT,
	ENEMYSCRIPT,
	EVENTCOLSCRIPT,
	FADEINOUTSCRIPT,
	FINALCRANEHOOKSCRIPT,
	GAMEPLAYBGSCRIPT,
	GAMESYSTEMMGRSCRIPT,
	GRABLINESCRIPT,
	GRABSCRIPT,
	GRABTAILSCRIPT,
	HOLDAIMSCRIPT,
	HPUISCRIPT,
	LAYERMGRSCRIPT,
	LEVELCHANGEEVENTCOLSCRIPT,
	MAINFLASHSCRIPT,
	MAINLIGHTONSCRIPT,
	MAINLOGOUI,
	MAINPARTICLESCRIPT,
	MAINSMOKESCRIPT,
	MAINUISCRIPT,
	MAPOBJSCRIPT,
	MENUUISCRIPT,
	MESSENGERSCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	PLAYEREFFECTSCRIPT,
	PLAYERSCRIPT,
	QTESCRIPT,
	REDCARGOSCRIPT,
	SEARCHBARSCRIPT,
	SIMPLEWALLSCRIPT,
	TILECOLSCRIPT,
	TROOPERSCRIPT,
	TURRETBODYSCRIPT,
	TURRETGUNSCRIPT,
	TURRETLASERSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
